steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/pam:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pam:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'beta'
      - 'run'
      - 'deploy'
      - 'pam'
      - '--image'
      - 'gcr.io/$PROJECT_ID/pam:$COMMIT_SHA'
      - '--allow-unauthenticated'
      - '--max-instances'
      - '4'
      - '--set-secrets'
      - '/secrets/config.yaml=pam-config:latest,/secrets/creds.json=pam-creds:latest'
      - '--region'
      - 'us-west1'
images:
  - 'gcr.io/$PROJECT_ID/pam:$COMMIT_SHA'